name: Build Android (APK & AAB)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Build APK
        uses: game-ci/unity-builder@v2
        with:
          projectPath: .
          unityVersion: 2022.3.40f1
          targetPlatform: Android
          buildName: KelimeArenasi
          versioning: Semantic
          androidExportType: apk
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kelimearenasi-apk
          path: build/Android/*.apk

      - name: Build AAB
        uses: game-ci/unity-builder@v2
        with:
          projectPath: .
          unityVersion: 2022.3.40f1
          targetPlatform: Android
          buildName: KelimeArenasi
          versioning: Semantic
          androidExportType: aab
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: kelimearenasi-aab
          path: build/Android/*.aab
