name: Build Android (APK & AAB)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.0
        with:
          tool-cache: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Docker sanity check
        run: |
          docker --version
          docker info || true
          df -h

      # (İlk denemede cache'i kapalı tutabilirsiniz)
      # - name: Cache Library
      #   uses: actions/cache@v4
      #   with:
      #     path: Library
      #     key: Library-${{ runner.os }}-${{ hashFiles('**/Packages/manifest.json') }}

      - name: Build APK
        uses: game-ci/unity-builder@v4
        with:
          projectPath: .
          unityVersion: 2022.3.40f1
          targetPlatform: Android
          androidExportType: apk
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - uses: actions/upload-artifact@v4
        with:
          name: kelimearenasi-apk
          path: build/Android/*.apk

      - name: Build AAB
        uses: game-ci/unity-builder@v4
        with:
          projectPath: .
          unityVersion: 2022.3.40f1
          targetPlatform: Android
          androidExportType: aab
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - uses: actions/upload-artifact@v4
        with:
          name: kelimearenasi-aab
          path: build/Android/*.aab
